In [2]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 50.2 MB/s  0:00:006m0:00:01
Downloading numpy-2.4.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 45.6 MB/s  0:00:006m0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.4.6 pandas-3.0.3

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

In [4]:
df = pd.DataFrame(
    {
        "이름": ['강은수', '조재영', '이한솔', '뽀로로'],
        "학과": ['언어학', '국문학', '언어학', '역사학'],
        "학년": [2, 3, 1, 4], 
        "국어": [88, 72, 95, 60],
        "수학": [75, 88, 82, 50],
        "영어": [90, 79, 85, 70],
    }
)
print(df)

    이름   학과  학년  국어  수학  영어
0  강은수  언어학   2  88  75  90
1  조재영  국문학   3  72  88  79
2  이한솔  언어학   1  95  82  85
3  뽀로로  역사학   4  60  50  70

In [9]:
print(df.shape)
print(df.columns)
print(df.index)
print(df.dtypes)

(4, 6)
Index(['이름', '학과', '학년', '국어', '수학', '영어'], dtype='str')
RangeIndex(start=0, stop=4, step=1)
이름      str
학과      str
학년    int64
국어    int64
수학    int64
영어    int64
dtype: object

In [14]:
print(df.head(2))
print(df.tail(2))

    이름   학과  학년  국어  수학  영어
0  강은수  언어학   2  88  75  90
1  조재영  국문학   3  72  88  79
    이름   학과  학년  국어  수학  영어
2  이한솔  언어학   1  95  82  85
3  뽀로로  역사학   4  60  50  70

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      4 non-null      str
 1   학과      4 non-null      str
 2   학년      4 non-null      int64
 3   국어      4 non-null      int64
 4   수학      4 non-null      int64
 5   영어      4 non-null      int64
dtypes: int64(4), str(2)
memory usage: 324.0 bytes

In [16]:
df.describe()

             학년         국어         수학         영어
count  4.000000   4.000000   4.000000   4.000000
mean   2.500000  78.750000  73.750000  81.000000
std    1.290994  15.777093  16.700798   8.602325
min    1.000000  60.000000  50.000000  70.000000
25%    1.750000  69.000000  68.750000  76.750000
50%    2.500000  80.000000  78.500000  82.000000
75%    3.250000  89.750000  83.500000  86.250000
max    4.000000  95.000000  88.000000  90.000000

In [17]:
df2 = df.set_index('이름')
df2

      학과  학년  국어  수학  영어
이름
강은수  언어학   2  88  75  90
조재영  국문학   3  72  88  79
이한솔  언어학   1  95  82  85
뽀로로  역사학   4  60  50  70